### ISSUE TITLE
Execution failed for task ':shadowJar'. > java.lang.AbstractMethodError (no error message)

### ISSUE THREAD

**Issue by askvortcov** [micronaut-guides/micronaut-function-aws-lambda#4]
Fresh generated project can not be built. 
Steps to reproduce:

    >.../mn $ mn --version
    | Micronaut Version: 1.0.1
    | JVM Version: 1.8.0_141
    
    >.../mn $ mn create-function awsfunction && cd awsfunction
    | Generating Java project...
    | Function created at /Users/askvortcov/programming/softec.be/mn/awsfunction
    
    >.../awsfunction $ vi build.gradle
    >.../awsfunction $ # comment block in build.gradle starting with if(new File("${System.getProperty("user.home")}/.aws/credentials
    
    >.../awsfunction $ ./gradlew build
    
    > Task :compileJava
    Note: Creating bean classes for 1 type elements
    
    > Task :shadowJar FAILED
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':shadowJar'.
    > java.lang.AbstractMethodError (no error message)
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 3s
    7 actionable tasks: 7 executed
 
Stacktrace gives:

    org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':shadowJar'.
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
            at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
    ....
    Caused by: java.lang.AbstractMethodError
            at com.github.jengelman.gradle.plugins.shadow.transformers.Transformer$modifyOutputStream$2.call(Unknown Source)
            at com.github.jengelman.gradle.plugins.shadow.transformers.Transformer$modifyOutputStream$2.call(Unknown Source)
            at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$_processTransformers_closure1.doCall(ShadowCopyAction.groovy:133)
            at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction.processTransformers(ShadowCopyAction.groovy:131)

I've tracked it down to the line `runtime "com.amazonaws:aws-lambda-java-log4j2:1.0.0"` in `build.gradle` disabling which fixes the build. (upgrading to `1.1.0` didn't help)

**Comment by iiglesiasg** [comment]
Fixed with
`shadowJar {
    transform(com.github.jengelman.gradle.plugins.shadow.transformers.Log4j2PluginsCacheFileTransformer)
    mergeServiceFiles()
}`

**Comment by askvortcov** [comment]
Does not happen in version 1.0.4.
