### ISSUE TITLE
SAM Local Inovke Fails with ClassNotFoundException: MicronautRequestStreamHandler

### ISSUE THREAD

**Issue by akefirad** [micronaut-guides/micronaut-function-aws-lambda#9]
I downloaded a fresh copy of the project and tried to run it, but it fails with the following message. Can someone please take a look. Thanks.
```
# sam local invoke ViesVatValidatorFunction -e event.json                   
Invoking io.micronaut.function.aws.MicronautRequestStreamHandler (java8)
2019-12-02 17:16:35 Found credentials in shared credentials file: ~/.aws/credentials

Fetching lambci/lambda:java8 Docker container image......
Mounting /home/rad/works/micronaut-function-aws-lambda-master/complete/vies-vat-validator/build/libs/complete/vies-vat-validator-0.1-all.jar as /var/task:ro,delegated inside runtime container
START RequestId: 348cd87a-7932-159b-a9de-24b5a9a066b4 Version: $LATEST
java.lang.ClassNotFoundException: io.micronaut.function.aws.MicronautRequestStreamHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)

Exception in thread "main" java.lang.Error: java.lang.RuntimeException: java.lang.RuntimeException: Unexpected status code from invocation/response: 299
        at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:65)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Unexpected status code from invocation/response: 299
        at lambdainternal.LambdaRuntime.reportDone(LambdaRuntime.java:227)
        at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:366)
        at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63)
        ... 3 more
Caused by: java.lang.RuntimeException: Unexpected status code from invocation/response: 299
        at lambdainternal.LambdaRuntime.reportDone(LambdaRuntime.java:224)
        ... 5 more
```
**UPDATE**
Ok that was a naming issue and I fixed it. But now I'm getting this:
```
# sam local invoke ViesVatValidatorFunction -e src/test/resources/event.json
Invoking io.micronaut.function.aws.MicronautRequestStreamHandler (java8)
2019-12-02 17:37:34 Found credentials in shared credentials file: ~/.aws/credentials
Decompressing /home/rad/works/vies-vat-validato/build/libs/vies-vat-validator-0.1-all.jar

Fetching lambci/lambda:java8 Docker container image......
Mounting /tmp/tmpx9rc294s as /var/task:ro,delegated inside runtime container
START RequestId: 9defde85-7b59-10d4-8e0d-4e0924e76465 Version: $LATEST
java.lang.Exception: Class io.micronaut.function.aws.MicronautRequestStreamHandler has no public zero-argument constructor
Caused by: java.lang.NoSuchMethodException: io.micronaut.function.aws.MicronautRequestStreamHandler.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)

Exception in thread "main" java.lang.Error: java.lang.RuntimeException: java.lang.RuntimeException: Unexpected status code from invocation/response: 299
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:65)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Unexpected status code from invocation/response: 299
	at lambdainternal.LambdaRuntime.reportDone(LambdaRuntime.java:227)
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:366)
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63)
	... 3 more
Caused by: java.lang.RuntimeException: Unexpected status code from invocation/response: 299
	at lambdainternal.LambdaRuntime.reportDone(LambdaRuntime.java:224)
	... 5 more
```

**Comment by akefirad** [comment]
For the record I also deployed it on AWS and it fails with the same error :disappointed:

**Comment by akefirad** [comment]
OK it seems having the constructor as `protected` is the issue. I managed to get it working but a simple and empty class inheriting from `MicronautRequestStreamHandler` and use it as the handler. Feel free to close the issue.

**Comment by Giesch** [comment]
I just ran into these same two error messages. Ideally, the instructions in the guide would be enough to pass the tests without coming to this repo. I'd like to change the guide to recommend both that users should change the path in the template yaml, and edit the generated build.gradle to include the 1.3.5 version of micronaut-function-aws ([which doesn't require subclassing the stream handler](https://github.com/micronaut-guides/micronaut-function-aws-lambda/commit/d28caf3d2d360c6bc27d43ec5136133a6398210c)).

Is there some flag we could pass to mn to specify dependency versions?

**Comment by Giesch** [comment]
Perhaps this is a separate issue, but the lambda from the guide as written (with micronaut-function-aws 1.3.5) ends up with a latency of about 26 seconds via api gateway with a cold start. Subsequent calls are about 600ms. There's a previous issue about startup time, but I thought 1.3.5's stream handler resolved that. Am I misunderstanding something about aws lambda? Is there some configuration to the default generated lambda that I should be changing?

**Comment by akefirad** [comment]
I'm not aware of the slowness issue. Anyway increasing the memory size significantly reduces the cold start time.

**Comment by ilopmar** [comment]
Fixed in https://github.com/micronaut-guides/micronaut-function-aws-lambda/commit/8ba04258d57aa2ef1d3d206dd1027365957526b5 and https://github.com/micronaut-guides/micronaut-function-aws-lambda/commit/8ba04258d57aa2ef1d3d206dd1027365957526b5
